# Generated by Django 3.1.5 on 2021-03-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=100)),
                ('patient_situation', models.CharField(max_length=100)),
                ('pin_code', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
