# Generated by Django 3.1.5 on 2021-03-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210328_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalmodel',
            name='beds',
            field=models.IntegerField(default=1),
        ),
    ]
