# Generated by Django 3.1.5 on 2021-03-28 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hospitalmodel_beds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalmodel',
            old_name='patient_situation',
            new_name='critical_level',
        ),
        migrations.RenameField(
            model_name='hospitalmodel',
            old_name='time',
            new_name='time_slot',
        ),
    ]
